# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20161107_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='admin_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_responsible_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
