# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_application_resolution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('resolution', '-ctime'), 'permissions': (('can_list_social_applications', 'Can list social applications'), ('can_view_social_applications', 'Can view social applications'), ('can_resolve_social_applications', 'Can resolve social applications'), ('can_list_content_applications', 'Can list content applications'), ('can_view_content_applications', 'Can view content applications'), ('can_resolve_content_applications', 'Can resolve content applications'), ('can_resolve_applications', 'Can resolve applications'))},
        ),
    ]
