# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20161107_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
