# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20161109_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
