# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20161109_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='reason_raw',
            field=models.TextField(verbose_name='reason'),
        ),
    ]
