# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20161110_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='resolution',
            field=models.TextField(blank=True),
        ),
    ]
