# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_flag_resolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='created',
            new_name='ctime',
        ),
    ]
