# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20161111_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
