# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20161111_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={'ordering': ['-ctime'], 'permissions': (('can_list_social_flags', 'Can list social flags'), ('can_view_social_flags', 'Can view social flags'), ('can_resolve_social_flags', 'Can resolve social flags'), ('can_list_content_flags', 'Can list content flags'), ('can_view_content_flags', 'Can view content flags'), ('can_resolve_content_flags', 'Can resolve content flags'), ('can_resolve_flags', 'Can resolve flags'))},
        ),
        migrations.RemoveField(
            model_name='ban',
            name='flag',
        ),
        migrations.AddField(
            model_name='ban',
            name='flags',
            field=models.ManyToManyField(blank=True, to='administration.Flag', verbose_name='Pertinent flags'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='body_raw',
            field=models.TextField(help_text='Describe\n    the issue with the content or the user.  Be as specific as possible,\n    including as many details and as much evidence as you can.  Markdown is\n    allowed.', verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag_type',
            field=models.CharField(choices=[('s', 'Social'), ('c', 'Content')], help_text="Pick 'content' if the\n        issue is with the content of the object, such as a violation of the\n        acceptable upload policy.  Pick 'social' if the issue is with the way\n        the creator of the content is behaving, such as a violation of the\n        terms of service.", max_length=1),
        ),
        migrations.AlterField(
            model_name='flag',
            name='subject',
            field=models.CharField(help_text='Briefly describe\n    the issue with the content or user. (100 characters)', max_length=100),
        ),
    ]
