language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - pandoc
install: "pip install -r requirements.txt"
script:
  - "make test-travis"
after_success:
  - ./run-coveralls.sh
