# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitystream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-activity_time']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('USER:REG', 'User: registered'), ('USER:LOGIN', 'User: logged in'), ('USER:LOGOUT', 'User: logged out'), ('USER:PWCHANGE', 'User: password changed'), ('USER:PWRESET', 'User: password reset'), ('PROFILE:UPDATE', 'User: profile updated'), ('PROFILE:VIEW', 'User: profile viewed'), ('ADMINFLAG:CREATE', 'Administration flag: created'), ('ADMINFLAG:UPDATE', 'Administration flag: updated'), ('ADMINFLAG:DELETE', 'Administration flag: deleted'), ('ADMINFLAG:VIEW', 'Administration flag: viewed'), ('GROUP:CREATE', 'Group: created'), ('GROUP:UPDATE', 'Group: updated'), ('GROUP:DELETE', 'Group: deleted'), ('GROUP:VIEW', 'Group: viewed'), ('SOCIAL:WATCH', 'Social: watch user'), ('SOCIAL:UNWATCH', 'Social: unwatch user'), ('SOCIAL:BLOCK', 'Social: block user'), ('SOCIAL:UNBLOCK', 'Social: unblock user'), ('SOCIAL:FAVORITE', 'Social: favorite submission'), ('SOCIAL:UNFAVORITE', 'Social: unfavorite submission'), ('SOCIAL:RATE', 'Social: rate submission'), ('SOCIAL:ENJOY', 'Social: enjoy submission'), ('SUBMISSION:CREATE', 'Submission: created'), ('SUBMISSION:UPDATE', 'Submission: updated'), ('SUBMISSION:DELETE', 'Submission: deleted'), ('SUBMISSION:VIEW', 'Submission: viewed'), ('FOLDER:CREATE', 'Folder: created'), ('FOLDER:UPDATE', 'Folder: updated'), ('FOLDER:DELETE', 'Folder: deleted'), ('FOLDER:VIEW', 'Folder: viewed'), ('FOLDER:SORT', 'Folder: sorted'), ('TAG:CREATE', 'Tag: tag created'), ('TAG:TAG', 'Tag: tagged item created'), ('COMMENT:CREATE', 'Comment: created'), ('COMMENT:UPDATE', 'Comment: updated'), ('COMMENT:DELETE', 'Comment: deleted'), ('PROMOTION:CREATE', 'Promotion: created'), ('PROMOTION:RETIRED', 'Promotion: retired'), ('PUBLISHER:CREATE', 'Publisher: created'), ('PUBLISHER:UPDATE', 'Publisher: updated'), ('PUBLISHER:DELETE', 'Publisher: deleted'), ('PUBLISHER:VIEW', 'Publisher: viewed'), ('PUBLISHER:CLAIMED', 'Publisher: claimed'), ('SEARCH:SEARCH', 'Search: run')], max_length=50),
        ),
    ]
