# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitystream', '0002_auto_20161030_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
