# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitystream', '0006_auto_20161031_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('user:reg', 'user: registered'), ('user:login', 'user: logged in'), ('user:logout', 'user: logged out'), ('user:pwchange', 'user: password changed'), ('user:pwreset', 'user: password reset'), ('profile:update', 'user: profile updated'), ('profile:view', 'user: profile viewed'), ('adminflag:create', 'administration flag: created'), ('adminflag:update', 'administration flag: updated'), ('adminflag:delete', 'administration flag: deleted'), ('adminflag:view', 'administration flag: viewed'), ('group:create', 'group: created'), ('group:update', 'group: updated'), ('group:delete', 'group: deleted'), ('social:watch', 'social: watch user'), ('social:unwatch', 'social: unwatch user'), ('social:block', 'social: block user'), ('social:unblock', 'social: unblock user'), ('social:message', 'social: message user'), ('social:favorite', 'social: favorite submission'), ('social:unfavorite', 'social: unfavorite submission'), ('social:rate', 'social: rate submission'), ('social:enjoy', 'social: enjoy submission'), ('submission:create', 'submission: created'), ('submission:update', 'submission: updated'), ('submission:delete', 'submission: deleted'), ('submission:view', 'submission: viewed'), ('folder:create', 'folder: created'), ('folder:update', 'folder: updated'), ('folder:delete', 'folder: deleted'), ('folder:view', 'folder: viewed'), ('folder:sort', 'folder: sorted'), ('tag:create', 'tag: tag created'), ('tag:tag', 'tag: tagged item created'), ('comment:create', 'comment: created'), ('comment:delete', 'comment: deleted'), ('promotion:create', 'promotion: created'), ('promotion:retire', 'promotion: retired'), ('ad:create', 'ad: created,'), ('ad:update', 'ad: update'), ('ad:golive', 'ad: went live'), ('ad:retire', 'ad: retired'), ('publisher:create', 'publisher: created'), ('publisher:update', 'publisher: updated'), ('publisher:delete', 'publisher: deleted'), ('publisher:view', 'publisher: viewed'), ('publisher:claimed', 'publisher: claimed'), ('search:basic_search', 'search: basic search run')], max_length=50),
        ),
    ]
