# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='usermgmt.FriendGroup'),
        ),
        migrations.AddField(
            model_name='submission',
            name='folders',
            field=models.ManyToManyField(blank=True, through='submissions.FolderItem', to='submissions.Folder'),
        ),
        migrations.AddField(
            model_name='submission',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderitem',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Folder'),
        ),
        migrations.AddField(
            model_name='folderitem',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='submissions',
            field=models.ManyToManyField(through='submissions.FolderItem', to='submissions.Submission'),
        ),
    ]
