# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='enjoy_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
