# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20161028_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mtime',
            field=models.DateTimeField(blank=True),
        ),
    ]
