# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20161028_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
