# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 06:21
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('submissions', '0004_auto_20161028_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
