# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_submission_cover_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='ctime',
            field=models.DateTimeField(),
        ),
    ]
