# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_auto_20161107_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='counts',
            field=models.CharField(default='{"counts": {"words": 0, "paragraphs: 0}}', max_length=250),
            preserve_default=False,
        ),
    ]
