# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20161028_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
