# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_promotion_promotion_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('cover', models.ImageField(upload_to=b'')),
                ('banner', models.ImageField(upload_to=b'')),
                ('description_raw', models.TextField()),
                ('description_rendered', models.TextField()),
                ('featured_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='adlifecycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adlifecycle',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_end_date',
            field=models.DateField(null=True),
        ),
    ]
