# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_auto_20161106_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
