# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_auto_20161106_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'permissions': (('can_highlight', 'Can create highlight permissions'),)},
        ),
    ]
