# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted_by_object_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body_raw',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
