# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitify', '0005_auto_20161204_0003'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherpage',
            name='calls',
            field=models.ManyToManyField(to='submitify.Call'),
        ),
        migrations.AddField(
            model_name='publisherpage',
            name='managed_calls',
            field=models.BooleanField(default=True),
        ),
    ]
