# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_auto_20161204_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisherpage',
            name='managed_calls',
        ),
    ]
