# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_remove_publisherpage_managed_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('body_raw', models.TextField()),
                ('body_rendered', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='publisherpage',
            old_name='body',
            new_name='body_raw',
        ),
        migrations.AddField(
            model_name='publisherpage',
            name='body_rendered',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitem',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.PublisherPage'),
        ),
    ]
