# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0005_auto_20161204_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitem',
            name='mtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publisherpage',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_publisher_page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisherpage',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
