# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0006_auto_20161204_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body_raw',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='publisherpage',
            name='body_raw',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='publisherpage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_publisher_page', to=settings.AUTH_USER_MODEL),
        ),
    ]
