# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=1)),
                ('subject_id', models.PositiveIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_source', to=settings.AUTH_USER_MODEL)),
                ('subject_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_raw', models.TextField(blank=True)),
                ('profile_rendered', models.TextField(blank=True)),
                ('attributes', models.TextField(blank=True)),
                ('blocked_users', models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('favorited_submissions', models.ManyToManyField(to='submissions.Submission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched_users', models.ManyToManyField(related_name='watched_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
