# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20161028_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('W', 'Watch'), ('M', 'Message'), ('F', 'Favorite'), ('R', 'Rating'), ('E', 'Enjoy'), ('S', 'Submission comment'), ('C', 'Comment reply'), ('P', 'Promote'), ('H', 'Highlight'), ('c', 'Application claimed'), ('r', 'Application resolved')], max_length=1),
        ),
    ]
