# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20161027_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_groups',
            field=models.ManyToManyField(to='usermgmt.FriendGroup'),
        ),
    ]
