# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20161020_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorited_submissions',
            field=models.ManyToManyField(related_name='favorited_by', to='submissions.Submission'),
        ),
    ]
