# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_profile_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('W', 'Watch'), ('M', 'Message'), ('F', 'Favorite'), ('R', 'Rating'), ('E', 'Enjoy'), ('S', 'Submission comment'), ('C', 'Comment reply'), ('P', 'Promote'), ('H', 'Highlight'), ('c', 'Application claimed'), ('r', 'Application resolved'), ('f', 'Flag created against'), ('p', 'Flag participant joined'), ('s', 'Flag resolved'), ('m', 'Flag commented on')], max_length=1),
        ),
    ]
